repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    # Verify YAML syntax
    - id: check-yaml
      name: "Check YAML"
      description: "Verify YAML syntax"
      args:
      - --allow-multiple-documents
    # Trims trailing whitespaces
    - id: trailing-whitespace
      name: "Trailing Whitespaces"
      description: "Trims trailing whitespaces"
    # Protect Master from direct checkins
    - id: no-commit-to-branch
      name: "No Commits to Master"
      description: "Protect Master from direct checkins"
      args:
      - --branch=master
      - --branch=main
    # Check for files that contain merge conflict strings.
    - id: check-merge-conflict
      name: "MergeRequests conflicts"
      description: "Check for files that contain merge conflict strings."
      args:
      - --assume-in-merge
-   repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.72.1
    hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terragrunt_fmt
